import './style.css';
import { renderHeader } from './src/components/header/header.js';
import { createHeaderLinks } from "./src/components/header/headerLinks/headerLinks.js";
import { renderNavBar } from './src/components/header/navBar/navBar.js';
import { createNavBarMenu } from './src/components/header/navBarMenu/navBarMenu.js';
import { createImageContainer } from './src/components/main/gallery/gallery.js';
import { imagesRandom } from "./src/components/main/imagesRandom/imagesRandom.js";
import { searchImages } from "./src/components/main/searchImages/searchImages.js";
import { createShowMoreButton } from "./src/components/main/showMore/showMore.js";
import { createFooter } from "./src/components/footer/footer.js";
import { footerLinks } from "./src/components/footer/footerLinks/footerLinks.js";

renderHeader();
createHeaderLinks();
renderNavBar();
createNavBarMenu();
createImageContainer();
imagesRandom();
searchImages();
createShowMoreButton();
createFooter();
footerLinks();